[project]
name = "moba"
version = "1.0.0"
requires-python = ">=3.10"
description = "Mixture of Block Attention is the MoE for Looong-Context LLMs"
readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}